spring:
  application:
    name: shopPoc
  jpa:
    open-in-view: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

shoppoc:
  user:
    enabled: true
  catalog:
    enabled: true
  order:
    enabled: true
  payment:
    provider: stub
